backend/impact/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('mainApp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

backend/mainApp/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from django.contrib.auth.decorators import login_required
from . import views

from impact import settings


app_name = 'mainApp' # Name space for the url links in templates
if settings.PROJECT_STATUS.lower() == "TERMINATED".lower():

    urlpatterns = [
        path('', views.terminatedProjectIndex, name='index'),
        path('about.html', views.loginDisabledAbout, name='about'),
        path('contact.html', views.loginDisabledContact, name='contact')
    ]
else:
    urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),

        path('search', views.SearchView.as_view(), name='search'),

        path('project/<int:project_id>', views.ProjectView.as_view(), name='projectDetail'),
        path('project/vote', views.VoteProject.as_view(), name='voteProject'),

        path('propositon/<int:proposition_id>', views.PropositionView.as_view(), \
            name='propositionDetail'),
        path('comment/add', views.AddNewCommentView.as_view(),
            name='addNewComment'),
        path('proposition/sign', views.SignProposition.as_view(), name='signProposition'),
        path('proposition/add', login_required(views.AddNewProposition.as_view()), name='addNewProposition'),
        path('add_vote_comment', views.AddVoteComment.as_view(),
            name='addVoteComment'),

        path('accounts/create', views.AccountsCreate.as_view(),
            name='account_create'),
        path('activate/<uid>/<token>', views.AccountsCreate.as_view(),
            name='activateAccount'),
        path('accounts/profile/',
            login_required(views.AccountsProfile.as_view()),
                name='accounts_profile'
        ),

        path('manager/', login_required(views.ManagerView.as_view()),
            name='manager'),
        path('about.html', views.AboutView.as_view(), name='about'),
        path('contact.html', views.ContactView.as_view(), name='contact')
    ]

backend/mainApp/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.sessions.backends.db import SessionStore
from django.shortcuts import get_object_or_404, render
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.core.serializers import serialize
from django.utils.functional import SimpleLazyObject
from django.urls import reverse
from django.views import generic
from django.db.utils import IntegrityError
from django.db.models import Q
from django.db.models import Count
from .models import *
from .forms import *
from django.core.mail import send_mail
from impact import settings
from django.utils.decorators import classonlymethod


import urllib.parse
import random
import statistics
import re
from datetime import datetime

from django.template.loader import get_template
from django.template import Context

"""
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer
from sumy.nlp.stemmers import Stemmer
from sumy.utils import get_stop_words
"""

LANGUAGE = "french"
SUMMARY_SENTENCES_COUNT = 3
MESSAGE_SEVERITIES = ["primary", "secondary", "success", "danger", "warning",
    "info", "light", "dark"]


def render_comment(comment):
    if not comment.approved:
        raise AttributeError(
            "The comment should be approved to be displayed."
        )
    author = "Anne Ho-Nihm";
    if comment.user is not None and comment.name_displayed:
        author = "%s %s" % (comment.user.first_name, comment.user.last_name)

    approved_details = None
    if not comment.name_displayed:
            approved_details = "Commentaire anonyme validé"

    image_ids = [22, 325, 628, 1, 455, 786, 602]
    r = random.randint(0,len(image_ids)-1)
    context = {
        "profile_picture": "https://picsum.photos/id/%d/200/200" % image_ids[r],
        "author_name": author,
        "comment": comment.comment,
        "create_date": comment.create_datetime,
        "approved_details": approved_details,
    }

    return render_to_string("mainApp/comment_detail.html",  context)


class AboutView(generic.View):
    def get(self, request, *args, **kwargs):

        context = {
            "page_title": "À propos",
        }
        return render(request, 'mainApp/about.html', context)

class ContactView(generic.View):
    def get(self, request, *args, **kwargs):

        context = {
        "page_title": "Contact",
        }
        return render(request, 'mainApp/contact.html', context)

def terminatedProjectIndex(request):
    print("settings.PROJECT_PDF_SUMMARY_FILEPATH = " + settings.PROJECT_PDF_SUMMARY_FILEPATH)
    return render(request, "mainApp/terminatedProject.html", {
        'disableLogin': True,
        "city_name": settings.CITY_NAME,
        "report_pdf_path": settings.PROJECT_PDF_SUMMARY_FILEPATH,
    })

def loginDisabledAbout(request):
    return render(request, "mainApp/about.html", {'disableLogin': True})

def loginDisabledContact(request):
    return render(request, "mainApp/contact.html", {'disableLogin': True})

class IndexView(generic.View):
    def get(self, request, *args, **kwargs):

        visitor = Visitor.objects.get(pk=request.session["visitor_id"])

        projects = list(CityProject.objects.all())
        random.shuffle(projects)
        # Fetching the vote (integers) of the user for each project:
        votes = [ \
            ["", "", ""] if (v is None or v.vote==0) \
            else \
                ["full-active-vote", "", "has_voted"] if v.vote>0 else ["", "full-active-vote", "has_voted"] \
            for v in
                [p.cityprojectvote_set.all().filter(visitor=visitor).first() \
                    for p in projects\
                ] \
        ]
        propositions = list(Proposition.objects.filter(approved=True))
        random.shuffle(propositions)

        # Retrieving the last message, if any, and resetting since it will be
        # displayed by the HTML template:
        message = None
        if "message" in request.session:
            message = {
                "content": request.session["message"],
                "severity": MESSAGE_SEVERITIES[0]
            }

            if "severity" in request.session:
                if request.session["severity"] in MESSAGE_SEVERITIES:
                    message["severity"] = request.session["severity"]
                del request.session["severity"]

            del request.session["message"]

        context = {
            'projects_votes': list(zip(projects, votes)),
            "propositions": propositions,
            "star_range": list(range(5)),
            "message" : message,
        }
        return render(request, 'mainApp/index.html', context)

def _contextifyDetail(databaseObject):
    return {
            "title": databaseObject.title,
            "page_title": databaseObject.title,
            "description": databaseObject.description,
            "image": databaseObject.image,
        }

class AccountsCreate(generic.View):
    def get(self, request, *args, **kwargs):

        # Let's see if the account needs to approved:
        if "uid" in kwargs and "token" in kwargs:
            user = User.objects.get(pk=int(kwargs["uid"]))
            if UserTokenGenerator().check_token(user, kwargs["token"]):
                # If the token is valid, then the account is activated:
                user.is_active = True
                user.save()
                messages.add_message(request, messages.INFO, "Compte validé! " \
                    + "Tu peux t'authentifier ci-dessous:")
            return HttpResponseRedirect(reverse('login', args=()))

        new_user_form = NewUserForm()
        context = {
            'new_user_form': new_user_form,
            "page_title": "Création de compte",
        }
        return render(request, 'mainApp/acccount_create.html', context)

    def post(self, request, *args, **kwargs):
        new_user_form = NewUserForm(request.POST, request.FILES)
        if new_user_form.is_valid():
            new_user_form.set_site_name(request.scheme + "://" + str(get_current_site(request)))
            new_user_form.set_email_sender(settings.DEFAULT_FROM_EMAIL)
            new_user_form.save()

            messages.add_message(request, messages.INFO, 'Compte créé! Un email de confirmation a été envoyé. Merci d\'utiliser le lien dans le mail pour activer ton compte.')
            return HttpResponseRedirect(reverse('mainApp:accounts_profile', args=()))
        else:
            context = {
                'new_user_form': new_user_form,
            }
            return render(request, 'mainApp/acccount_create.html', context)

class ManagerView(generic.View):
    def get(self, request, *args, **kwargs):
        if request.user.groups.all().filter(name="Manager").count() < 1:
            messages.add_message(request, messages.WARNING, "Accès interdit! Tu as été redirigé vers ton compte.")
            return HttpResponseRedirect(reverse("mainApp:accounts_profile", args=()))

        context = {}
        context["include_manager_js"] = True

        managers = []
        for user in User.objects.all():
            if user.groups.all().filter(name="Manager").count() >0:
                managers.append(user)

        context["managers"] = managers
        projects = CityProject.objects.all()
        votes = list()
        comments = list()
        project_questions_answers = []
        answers_qty = []

        for project in projects:
            curr_votes = project.cityprojectvote_set.all()
            general_comments = []
            up_votes = 0
            down_votes = 0
            curr_answers_qty = 0
            for vote in curr_votes:
                if vote.vote > 0:
                    up_votes += 1
                else:
                    down_votes += 1
                if len(vote.comment)>0:
                    general_comments.append(vote.comment)
                    curr_answers_qty += 1
            votes.append("Votes: %d positifs / %d négatifs" % (up_votes, down_votes))

            comments.append(project.cityprojectcomment_set.all())
            curr_questions = project.cityprojectquestion_set.all()
            questions_answers = {}
            # Adding the general question of the project into the list of
            # questions, as if it was coming from the linked table:
            questions_answers["Commentaires généraux:"] =  general_comments

            for question in curr_questions:
                curr_answers = question.cityprojectanswer_set.all()
                curr_answers_qty += len(curr_answers)
                aggregated_answers = []
                if question.type == "YES_NO":
                    if len(curr_answers) > 0:
                        res = statistics.mean([x.numeric_answer for x in curr_answers])
                        aggregated_answers = ["{:.0f}".format((1-res)*100) + "% de oui" + " - %d réponse(s)" % len(curr_answers)]
                elif question.type == "RATING_STARS":
                    try:
                        res = statistics.mean([x.numeric_answer for x in curr_answers])
                        aggregated_answers = ["{:.2f}".format(res) +"/5 étoile(s) - %d réponse(s)" % len(curr_answers)]
                    except:
                        pass
                elif question.type == "RATING_10_5_0":
                    try:
                        aggregated_answers = []
                        total = len(curr_answers)
                        for i, desc in enumerate(CityProjectQuestion.ratings_10_5_0_values):
                            qty = len(curr_answers.filter(
                                numeric_answer=i)
                            )
                            aggregated_answers.append("{:.2f}".format(qty/total*100) + "% " + desc + " - %d réponse(s)" % qty)

backend/mainApp/templates/mainApp/comment_detail.html
<div class="comment">
    <div>
        <img src="{{ profile_picture }}" alt="profile" />
        <span class="author_name">{{ author_name }}</span>
        {% if approved_details %}
            <span class="comment_pill bg_blue">{{ approved_details }}</span>
        {% else %}
            <span class="comment_pill bg_purple">Utilisateur enregistré</span>
        {% endif %}
        <p class="create_date">{{ create_date }}</p>
    </div>
    <p>{{ comment|linebreaksbr }}</p>
</div>

backend/mainApp/templates/mainApp/contact.html
{% extends "mainApp/base.html" %}
{% load extras_tags %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-sm-12">
        <h3>Contact</h3>
            <p>Pour toute question à l’intention de l’équipe Citympact, merci d’écrire un mail à <a href="javascript:" data-contact="hello[at]citympact[dot]ch">hello[at]citympact[dot]ch</a>.</p>
        </div>
    </div>
</div>
{% endblock %}

backend/mainApp/templates/mainApp/detailView.html
{% extends "mainApp/base.html" %}
{% load extras_tags %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 text-center">
            <h1 class="{{ title_css_class }}">{{ title }}</h1>

            <h2 class="detail_subtitle">{{ subtitle }}</h2>
            <div class="details_view_gallery">
                {% if other_image_instances %}
                    <div class="details_view_gallery_buttons left"><svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                    </svg></div>
                {% endif %}
                <div class="details_view_gallery_images">
                    {% if image %}
                        <img src="{{ image.url|thumbnailize }}" alt="{{ title }}" alt=""/>
                    {% else %}
                        <img src="/static/mainApp/images/placeholder_image.jpg" alt="{{ title }}" alt=""/>
                    {% endif %}
                    {% if other_image_instances %}
                        {% for other_image_instance in other_image_instances %}
                            <img src="{{ other_image_instance.image.url|thumbnailize }}" alt="{{ title }}" alt="" class="detail_image"/>
                        {% endfor %}
                    {% endif %}
                </div>
                {% if other_image_instances %}
                    <div class="details_view_gallery_buttons right"><svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                    </svg></div>
                {% endif %}
            </div>
            <div class="opinion_detail_view_div text-start">
                <h4>{{ what_do_you_think }}</h4>
            </div>
            <p class="col-sm-12 text-start">{{ description|linebreaksbr }}</p>

            {% comment "CSRF token for the vote just below or for the sub project votes:" %}
            {% endcomment %}

            <input type="hidden" id="vote_csrf_token" value="{{ csrf_token }}" />

            {% if show_voting_box %}
            <div class="detail_view_voting" data-project-id="{{ project_id }}">
                <a class="upvote_button {{ upvote_class }}"><img src="/static/mainApp/images/upvote.png" alt="" height="66"></a>
                <h4>Donne ton avis</h4>
                <a class="downvote_button {{ downvote_class }}"><img src="/static/mainApp/images/downvote.png" alt="" height="66"></a>
            </div>
            {% endif %}

            <h2 class="detail_subtitle">Informations</h2>
            {% if up_votes %}
            <div class="detail_info_item">
                <img class="bg_green bigger_img" src="/static/mainApp/images/upvote.png" alt="" />
                <span>{{ up_votes }} votes positifs</span>
            </div>
            {% endif %}
            {% if down_votes %}
            <div class="detail_info_item">
                <img class="bg_red bigger_img" src="/static/mainApp/images/downvote.png" alt="" />
                <span>{{ down_votes }} votes négatifs</span>
            </div>
            {% endif %}
            <div class="detail_info_item">
                <img class="bg_purple" src="/static/mainApp/images/calendar.png" alt="" />
                <span>Créé le {{ create_date }}</span>
            </div>
            <div class="detail_info_item">
                <img class="bg_blue" src="/static/mainApp/images/eye.png" alt="" />
                <span>{{ views_count }} vues</span>
            </div>
            <div class="detail_info_item">
                <img class="bg_yellow" src="/static/mainApp/images/circle_star.png" alt="" />
                <span>{{ ranking }} {{ detail_type_text }} populaire</span>
            </div>
            {% if signatures %}
            <div class="detail_info_item">
                <img class="bg_green" src="/static/mainApp/images/sign.png" alt="" />
                <span>{{ signatures }} signatures</span>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="container pb-5">
    <div class="row">
        <div class="col-sm-12">
            <h2 class="detail_subtitle pt-5">Commentaires</h2>
            <button class="add_comment_button" id="comment_toggle_button"><img src="/static/mainApp/images/comment.png" alt="" /> Ajouter un commentaire</button>
            <div id="message_div"></div>
            <form id="comment_add" style="display: none;"
                action="{% url 'mainApp:addNewComment' %}"
                method="POST"
                enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row pb-4">
                    <div class="col-sm-12  mb-4">
                        <textarea name="comment" rows="8" cols="80" class="form-control" id="add_comment_textarea"></textarea>
                        <div class="invalid-feedback">
                            Merci d'insérer un commentaire.
                        </div>
                    </div>
                    {% if comment_user_name %}
                        <div class="col-sm-12"><input type="radio" name="publish_name" id="publish_name_true" value="true" checked="checked">  <label for="publish_name_true">Poster ce commentaire avec ton nom ({{ comment_user_name }}) ?</label>
                        </div>
                        <div class="col-sm-12">
                        <input type="radio" name="publish_name" id="publish_name_false" value="false">  <label for="publish_name_false">Poster ce commentaire sans afficher ton nom?</label><br><small class="ps-3">Les commentaires anonymes sont soumis à une validation et ne sont affichés qu'après leur approbation.</small>
                        </div>
                    {% else %}
                    <small>Ton commentaire sera publié anonymement mais sera soumis à approbation. Si tu ne veux pas attendre cette validation, tu peux <a href="{% url 'login' %}?next={{ login_next_url }}">t'authentifier ici</a>.</small>
                    </div>
                    {% endif %}
                    <input type="hidden" name="model_name" value="{{ model_name }}" />
                    <input type="hidden" name="id" value="{{ id }}" />
                    <div class="col-sm-12 mt-3 mb-3">
                        <button type="submit" class="account_button">Poster un commentaire</button>
                    </div>


            </form>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12" id="comments_div">
            {% for comment in authenticated_comments %}
                {{ comment }}
            {% endfor %}
            {% for comment in anynymous_comments %}
                {{ comment }}
            {% endfor %}
        </div>
    </div>
</div>


{% if proposed_projects_and_votes %}
<div class="container background_projects">
    <h1 class="detail_subtitle">{{ proposed_projects_title }}</h1>
    <div class="row detail_row">
        {% for project, voteClasses in proposed_projects_and_votes %}
            <div data-project-id="{{ project.pk }}" data-project-vote="{{ vote }}" class="col-xs-12 col-sm-6 col-md-4 col-lg-3 detail_div">
                <div class="image_and_vote_buttons">
                    <a href="{% url 'mainApp:projectDetail' project.id %}"><img src="{{ project.image.url|thumbnailize }}" alt="{{ project.title }}" alt="" class="sliderThumbnail"/></a>
                    <a class="upvote_button {{ voteClasses.0 }}" href="#"><img src="/static/mainApp/images/upvote.png" alt="" height="66"></a>
                    <a class="downvote_button {{ voteClasses.1 }}" href="#"><img src="/static/mainApp/images/downvote.png" alt="" height="66"></a>
                    <p class="thanks_voting {{ voteClasses.2 }}">Merci d’avoir voté</p>
                </div>

                <h2><a href="{% url 'mainApp:projectDetail' project.id %}">{{ project.title }}</a></h2>
                <p>{{ project.summary }}</p>
                <div class="know-more"><a href="{% url 'mainApp:projectDetail' project.id %}">En savoir plus</a></div>
            </div>
        {% endfor %}
    </div>
    <div class="show_more_div"><a href="#" data-toggle-text="Montrer moins d'éléments">Afficher plus de projets</a></div>
</div>

<div id="new_proposition"><a href="{% url "mainApp:addNewProposition" %}">Soumettre une proposition</a></div>
{% endif %}

{% endblock %}

backend/mainApp/templates/mainApp/index.html
{% extends "mainApp/base.html" %}
{% load extras_tags %}

{% block content %}

<input type="hidden" id="vote_csrf_token" value="{{ csrf_token }}" />
<div class="container">
  <div class="row">
    <div class="col-sm-12">
        {% if messages %}
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }} pb-0" role="alert">
                  <p>{{ message }}</p>
              </div>
              {% endfor %}
          {% endif %}
        <div class="header">
                <div class="search-group">
                  <input type="text" class="form-control" placeholder="Que veux tu changer dans ta ville?" aria-label="Que veux tu changer dans ta ville?" aria-describedby="button-addon2" id="search-input" autocomplete="off">
                  <div class="suggestions-dropdown" style="display: none;">
                      <ul>
                          <li><a href="{% url 'mainApp:addNewProposition' %}">>> Soumettre une proposition</a></li>
                      </ul>
                  </div>
                </div>

        </div>
    </div>
  </div>
</div>
<div class="container pt-5">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="homepage_title">Que penses-tu de ces projets?</h1>
            {% if projects_votes %}
                <div class="row detail_row">
                    {% for project, voteClasses in projects_votes %}
                        <div data-project-id="{{ project.pk }}" data-project-vote="{{ vote }}" class="col-xs-12 col-sm-6 col-md-4 col-lg-3 detail_div">
                            <div class="image_and_vote_buttons">
                                <a href="{% url 'mainApp:projectDetail' project.id %}"><img src="{{ project.image.url|thumbnailize }}" alt="{{ project.title }}" alt="" class="sliderThumbnail"/></a>
                                <a class="upvote_button {{ voteClasses.0 }}" href="#"><img src="/static/mainApp/images/upvote.png" alt="" height="66"></a>
                                <a class="downvote_button {{ voteClasses.1 }}" href="#"><img src="/static/mainApp/images/downvote.png" alt="" height="66"></a>
                                <p class="thanks_voting {{ voteClasses.2 }}">Merci d’avoir voté</p>
                            </div>
                            <h2><a href="{% url 'mainApp:projectDetail' project.id %}">{{ project.title }}</a></h2>
                            <p>{{ project.summary }}</p>
                            <div class="know-more"><a href="{% url 'mainApp:projectDetail' project.id %}">En savoir plus</a></div>
                        </div>
                    {% endfor %}
                </div>
                <div class="show_more_div"><a href="#" data-toggle-text="Montrer moins d'éléments">Afficher plus de projets</a></div>
            {% else %}
                <p>Il n'y a pas encore de projets.</p>
            {% endif %}
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="homepage_title proposition_title">Donne ton avis - propositions en cours</h1>
            {% if propositions %}
                <div class="row detail_row">
                    {% for proposition in propositions %}
                        <div data-proposition-id="{{ proposition.pk }}" class="col-xs-12 col-sm-6 col-md-4 col-lg-3 detail_div">
                            {% if proposition.image %}
                                <a href="{% url 'mainApp:propositionDetail' proposition.id %}"><img src="{{ proposition.image.url|thumbnailize }}" alt="{{ proposition.title }}" alt="" class="sliderThumbnail"/></a>
                            {% else %}
                                <a href="{% url 'mainApp:propositionDetail' proposition.id %}"><img src="/static/mainApp/images/placeholder_image.jpg" alt="{{ proposition.title }}" alt="" class="sliderThumbnail"/></a>
                            {% endif %}
                            <div class="sign_proposition_div"><a href="#"><img src="/static/mainApp/images/sign.png" alt="" height="25"> Soutenir la proposition</a></div>
                            <h2><a href="{% url 'mainApp:propositionDetail' proposition.id %}">{{ proposition.title }}</a>
                            </h2>
                            <p class="">{{ proposition.summary }}</p>
                            <div class="know-more"><a href="{% url 'mainApp:propositionDetail' proposition.id %}">En savoir plus</a></div>
                        </div>
                    {% endfor %}
                </div>
                <div class="show_more_div"><a href="#" data-toggle-text="Montrer moins d'éléments">Afficher plus de propositions</a></div>
            {% else %}
                <p>Il n'y a pas encore de propositions.</p>
            {% endif %}

            <div id="new_proposition"><a href="{% url "mainApp:addNewProposition" %}">Soumettre une proposition</a></div>
        </div>
    </div>
</div>

{% endblock %}

backend/mainApp/templates/mainApp/interaction-email.html
<h1>Nouvelle interaction à valider</h1>
<p>{{ event}} sur la plateforme Citympact - {{ city_name }}:</p>
<div style="padding-left: 25px; border: 1px dotted black;">
    <h2>{{ item }}</h2>
    <p>Date et heure: {{ create_datetime }}<br>Auteur: {{ author }}</p>
    {% if title %}<h5>{{ title }}</h5>{% endif %}
    <p>{{ description }}</p>
    {% if image_url %}<p><img src="{{ image_url }}" alt=""></p>{% endif %}
    <p><a href="{{ link_url }}">{{ manage_item }}</a></p>
</div>"

backend/mainApp/templates/mainApp/new_proposition.html
{% extends "mainApp/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
            <img src="/static/mainApp/images/new_proposition.png" alt="" class="center_image"/>
            <form action="{% url "mainApp:addNewProposition" %}" method="POST"
                enctype="multipart/form-data" class="citympact_validated_form" >

                {% csrf_token %}
                <div class="form_row">
                    <label>Titre de la proposition:</label>
                    <input type="text" name="title" value="{{ title }}" size="50" class="form-control" />
                    <div class="invalid-feedback">
                       Please choose a username.
                    </div>
                </div>
                <div class="form_row">
                    <label>Image de la proposition:</label>
                    <input type="file" name="image" />
                </div>
                <div class="form_row">
                    <label>Description de la proposition:</label>
                    <textarea name="description" rows="8" class="form-control"></textarea>
                </div>
                <div class="form_row">
                    <label>Auteur·trice de la proposition:</label>
                    <input type="text" name="title" value="{{ user_full_name }}" disabled="disabled" />
                </div>
                <input type="submit" value="Enregistrer" class="account_button">
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/mainApp/templates/mainApp/sign_proposition.html
<h4 class="popup_title">Soutenir la proposition</h4>
<p>Es-tu sûr de soutenir la proposition intitulée :<br>
<em>{{ proposition_title }}</em>?
</p>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-xs-10">
            <form action="{% url "mainApp:signProposition" %}" method="POST">
            {% if registered_user_form %}
                <p>Pour soutenir la proposition, nous avons besoin des informations suivantes: </p>
                <div class="form_row">
                    <label class="text-start">Code postal:</label>
                        {{ registered_user_form.zip_code }}
                </div>
                <div class="form_row">
                    <label class="text-start">Ville:</label>
                        {{ registered_user_form.city }}
                </div>
                <div class="form_row">
                    <label class="text-start">Année de naissance:</label>
                        {{ registered_user_form.birth_year }}
                </div>
            {% endif %}

            <p><input type="checkbox" name="signature_checkbox" class="required-form-input" id="signature_checkbox"> <label for="signature_checkbox">Je, soussigné <strong>{{ first_name }} {{ last_name }}</strong>, soutiens la proposition.</label></p>
            <input type="hidden" name="proposition_id" value="{{ proposition_id}}" />
            </form>
        </div>
    </div>
</div>